import json
from collections.abc import AsyncGenerator

import httpx
import structlog

from fastapi_ollama_rag.core.config import settings
from fastapi_ollama_rag.models.chat import SearchResult

logger = structlog.get_logger(__name__)


async def generate_rag_response(
    query: str, context: list[SearchResult]
) -> AsyncGenerator[str, None]:
    """
    Constructs a strict RAG prompt using retrieved database chunks and streams the
    LLM's response token-by-token from the Ollama instance.
    """
    url = f"{settings.ollama_base_url}/api/chat"

    # Compile the retrieved database chunks into a single readable string
    context_text = "\n\n---\n\n".join(
        [
            f"Context Chunk (Score: {res.similarity_score:.2f}):\n{res.text}"
            for res in context
        ]
    )

    system_prompt = (
        "You are an expert AI assistant. Your task is to answer the user's question "
        "using ONLY the provided context below. "
        "If the context does not contain the answer, "
        "explicitly state that you do not know. "
        "Do not hallucinate outside the given information.\n\n"
        f"CONTEXT:\n{context_text}"
    )

    payload = {
        "model": settings.ollama_generation_model,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": query},
        ],
        "stream": True,
    }

    logger.info(
        "Initiating LLM generation stream...", model=settings.ollama_generation_model
    )

    # Custom timeout=None; LLM generation can take time depending on GPU/CPU
    async with httpx.AsyncClient(timeout=None) as client:
        try:
            async with client.stream("POST", url, json=payload) as response:
                response.raise_for_status()

                # Iterate over the raw byte stream as Ollama outputs it
                async for line in response.aiter_lines():
                    if line:
                        data = json.loads(line)
                        message = data.get("message", {})
                        content = message.get("content", "")

                        # Yield the exact token chunk generated by the model
                        if content:
                            yield content

                        # Stop the generator cleanly when Ollama signals completion
                        if data.get("done"):
                            logger.info("LLM generation stream completed...")
                            break

        except httpx.HTTPError as e:
            logger.error("Failed to connect to Ollama generation API!!!", error=str(e))
            yield "\n\n[Error: Connection to LLM generation service failed!!!]"
